# Generated by Django 5.0.4 on 2024-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
